PROJECT:
  PORT: 8080
  BASE_PATH: str = os.path.dirname(os.path.dirname(os.path.dirname((os.path.abspath(__file__)))))
DATABASE:
  MYSQL:
    USERNAME: 用户名
    PASSWORD: 密码
    HOST: 连接地址
    PORT: 3306
    DATABASE: 数据库名
  REDIS:
    HOST: 连接地址
    PASSWORD: 密码
    DB: 数据组
    PORT: 端口
    TIMEOUT: 5  # redis连接超时时间
